### ISSUE TITLE
Date/time of observation changes when editing

### ISSUE THREAD

**Issue by mmulholland** [olivierfriard/BORIS-kivy-app#1]
Moved this over from BORIS issues as it is app related:

I am using the app on a Samsung Galaxy tablet, collect the data, send the observations to the project on my PC using the project server. At that point, the dates and times match the actual date/time of the observation, then I went into the observations on my laptop (v 6.2.4, Windows 7) and edited a couple of independent variables that had been entered incorrectly, saved and then the date/time was automatically changed to the date/time I edited the observation on my laptop. 

Original observation after importing using the project server:
![image](https://user-images.githubusercontent.com/25001552/39595713-df246a38-4ed5-11e8-86b9-e721d48d1b19.png)

Same observation after editing an independent variable:
![image](https://user-images.githubusercontent.com/25001552/39595776-0763a022-4ed6-11e8-9198-4a96f72ea26c.png)

This does not happen when editing any variables when the data was collected using the Windows version, it only happens when using the Windows version to make an edit on data collected using the app.

Let me know if you need any other info! Thanks, Michele

**Comment by olivierfriard** [comment]
The bug was fixed in v. 0.2.3 of BORIS-App.
The observation date format in BORIS-App is now:
YYYY-MM-DD HH:mm:SS
The format will be checked before starting the observation.
BORIS will recognize this new format and do not update the date.

Thanks for reporting this

**Comment by mmulholland** [comment]
Where can I download v. 0.2.3? My app says that v 0.2.2 is the current version, and the website still has v. 0.2.2 on the download page. Thanks!

**Comment by olivierfriard** [comment]
from:
https://github.com/olivierfriard/BORIS-App/releases

​I will update the page ASAP

o​
