### ISSUE TITLE
Installing Boris App on Android using Python for Android

### ISSUE THREAD

**Issue by kyl10** [olivierfriard/BORIS-kivy-app#11]
Hi,

Does anyone know how to install Boris App on an android phone (Sony F5321) using Python for Android (or another app), since Kivy launcher is no longer available?

**Comment by olivierfriard** [comment]
Hi,
a new version of BORIS App is available.
An APK file is available, the Kivy launcher is no more required.
See https://github.com/olivierfriard/BORIS-App/releases

**Comment by kyl10** [comment]
Thanks for letting me know!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op ma 27 feb 2023 om 17:33 schreef Olivier Friard ***@***.***
