### ISSUE TITLE
Boris App can't find the .boris file in my device

### ISSUE THREAD

**Issue by nickn001** [olivierfriard/BORIS-kivy-app#13]
Hi, I recently downloaded the Boris app v0.4 , but it can't find the .boris file I directly imported from my computer to my android device (Samsung tablet and my Samsung phone).

![Screenshot_20230306-120829_BORIS App](https://user-images.githubusercontent.com/127073104/223017476-3008a59f-a853-48bb-9991-73aea8712afc.jpg)

**Comment by olivierfriard** [comment]
Hi,
where did you save your BORIS project file?

**Comment by nickn001** [comment]
> Hi,
> where did you save your BORIS project file?
> 

They are saved in "Documents" and "Download".

Besides, I have a little suggestion on the user guide page. I tried to find the guide on www.boris.unito.it, it was the guide for v0.2.2. I need to click on the 'Edit on Github' hyperlink to get the v0.4 guide, maybe you can change the url of the guide on www.boris.unito.it ?

**Comment by olivierfriard** [comment]
I will add the directory path to the file chooser to help the user to save the project file in the right directory.

The user guide was updated. Thank you for the tip!

**Comment by olivierfriard** [comment]
The storage path was added in the project chooser window in v. 0.5
Can you tell me what is the path that is displayed?

**Comment by nickn001** [comment]
Thanks a lot!!!!!!!!!!!! 
I can find my .boris file now.
If you mean the paths displayed, I think I can see every .boris file in Internal Storge. 
If you mean my .boris file, it is in storge/Download, and shown as "/storage/emulated/0/Download/file name.boris".
The current storage when I am looking for the files is always shown as "/storage/emulated/0", but it doesn't bother my use.


![WhatsApp Image 2023-03-09 at 19 55 40](https://user-images.githubusercontent.com/127073104/224015967-8beb0fea-b8f3-46e8-9a47-3a226aab8bd2.jpeg)
![WhatsApp Image 2023-03-09 at 20 00 15](https://user-images.githubusercontent.com/127073104/224017047-0a315821-2b2f-45d2-a38b-64355bf46dd8.jpeg)
