### ISSUE TITLE
No synchronization between observations and epoch time

### ISSUE THREAD

**Issue by Julien82000** [olivierfriard/BORIS-kivy-app#14]
Hello, I just downloaded Boris for live observation. When I work with the android app, the observations are not synchronized with the epoch time. Each new observation starts again at 00:00:00. 

Here is an example of what I get :

![image](https://user-images.githubusercontent.com/130649416/231715806-32dd61e1-bf49-4216-92c7-2b21d58bdc5a.png)

And this is what I want : 

![image](https://user-images.githubusercontent.com/130649416/231716290-e74272a8-6c66-4cdb-9fbf-05db285e291d.png)

Do you have any solutions for that ?

Thank you for your help,
Sincerely

**Comment by olivierfriard** [comment]
Hi Julien,

what version of BORIS-App are you using?

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
The issue should be fixed in v. 0.10 just released.
Please try and let me know
