### ISSUE TITLE
Point events and state events not mutually exclusive

### ISSUE THREAD

**Issue by truong-s** [olivierfriard/BORIS-kivy-app#15]
Hi!
We recently started using the Android app for live observation and it worked really well! One issue we had was we set a point event to be mutually exclusive with a state event, but when we pressed the button for the point event, it would not stop the state event. We checked whether the exclusion matrix was done correctly on PC and it works fine on the desktop version of BORIS (i.e. coding the point event would stop the state event, which is what we want). Is it possible to fix this for the phone app? We were using v. 0.7 and it seems the issue still occurs in v. 0.9. 
Thanks! - Suzanne

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
The issue should be fixed in v. 0.10 just released.
Please try and let me know

**Comment by truong-s** [comment]
Hi Olivier,
Thanks so much for addressing this. I updated it to v. 0.10 but unfortunately now the app seems to crash as soon as I press a behaviour no matter which one I select (the point event or the state event). Could there be a bug?
Thanks, Suzanne

**Comment by olivierfriard** [comment]
Yes, it was a bug.
It is now fixed in v. 0.11
Thank you for your collaboration
