### ISSUE TITLE
Error with mutually exclusive state events

### ISSUE THREAD

**Issue by Celia97-these** [olivierfriard/BORIS-kivy-app#18]
Hi, i recently started to use BORIS for my thesis. I'm facing a problem with the exclusion matrix : my behaviors are almost all mutually exclusive, yet when i launch an observation, a state event won't stop at the beginning of the other (the two of them are mutually exclusived). I checked my exclusion matrix multiple times, but can't find the solution. Maybe have i done something wrong ? 

I'm not sure this is the right place to ask this question, i apologize in advance if it's not the case. 

Thank you very much!

**Comment by olivierfriard** [comment]
Hi,
is it possible to have the BORIS project file in order to repeat the issue?

**Comment by Celia97-these** [comment]
Hi, Thank you for your quick answer. Here is the file. I must tell you that the project i work on is confidential, so thank you for not sharing it or making it public.  
Thank you very much !
Celia (from France )

    Le jeudi 4 juillet 2024 à 11:41:36 UTC+2, Olivier Friard ***@***.***> a écrit :  
 
 


Hi,
is it possible to have the BORIS project file in order to repeat the issue?

**Comment by olivierfriard** [comment]
You can send it to me by email. I assure you that I will not disclose your project to anyone.
