### ISSUE TITLE
Timer for Observations

### ISSUE THREAD

**Issue by mmulholland** [olivierfriard/BORIS-kivy-app#2]
Using v. 0.2.3
Can a timer be added like in the desktop version? We have no way of knowing how much time has past unless we use a separate timer/stopwatch/etc. It would be nice to have everything in-app. Thanks! 

As always I'll test any updates you make! -Michele

**Comment by olivierfriard** [comment]
Hi,
BORIS App was updated.
I will add a timer as soon as possible.
See https://github.com/olivierfriard/BORIS-App/releases

**Comment by olivierfriard** [comment]
A clock and a stopwatch were added in v. 0.7
