### ISSUE TITLE
BORIS App Independent variables issue

### ISSUE THREAD

**Issue by Kyanapike** [olivierfriard/BORIS-kivy-app#4]
There is an issue with some features to the 'Independent Variables' for my ethogram. This works fine on the Desktop but in the App I can enter the variables but it does not give me any option to save the data as there is only a 'Go back' button to the bottom of the screen which then does not save any of the data I have entered (
![img_7150 1](https://user-images.githubusercontent.com/46981498/51647122-40f10100-1fc7-11e9-9647-1520b2102233.JPG)

**Comment by olivierfriard** [comment]
This issue should be fixed in v. 0.8
