### ISSUE TITLE
Transfer from computer to device

### ISSUE THREAD

**Issue by cbgd** [olivierfriard/BORIS-kivy-app#7]
Hello, 
I can't create the  new directory to /sdcard/kivy/ to copy the extracted directory (BORIS-App-VERSION). I can't put "/" in title files...
(If the /sdcard/kivy directory does not exist on your Android device you must create it): this step doesn't work on my device.
Moreover, when i launch kivy, he propose an other directory for the files (/storage/emulated/0/kivy). Which one is the good one ?

Can you help me please ? 
I download the last version the Boris on computer and boris App and kivy.
I have a Samsung Galaxy Tab A

Thank you

**Comment by Askevh** [comment]
Hi,
I had the same issue and got it to work. I'm not sure whether it works for you as you said creating a new directory doesn't work on your device. But you could create the right directory by simply making a new folder.
/storage/emulated/0/ is the standard directory for internal files. I made a new folder called "kivy" in my internal storage (when in "my files") and copied the project to this folder. This worked for me (Samsung Galaxy Tab E).
Good luck!

**Comment by cbgd** [comment]
Hi, 
it doesn't work... 
have you some screenshot to explain me how to do ?

Here attached what i've done

Thank you for your help !
![Screenshot_20210519-092412_My Files](https://user-images.githubusercontent.com/84073575/118773088-bfeb6100-b884-11eb-844c-83029037268d.jpg)
![Screenshot_20210519-092421_My Files](https://user-images.githubusercontent.com/84073575/118773090-c11c8e00-b884-11eb-8cb7-bb33b70368ce.jpg)
![Screenshot_20210519-092435_My Files](https://user-images.githubusercontent.com/84073575/118773092-c11c8e00-b884-11eb-890a-cec38e278c7b.jpg)
![Screenshot_20210519-092459_My Files](https://user-images.githubusercontent.com/84073575/118773095-c1b52480-b884-11eb-9cd5-1b3c41e38f9f.jpg)

**Comment by Askevh** [comment]
Hi,
No need to make folders "emulated" and "0". Just the kivy folder should do the trick. See screenshot attached.
![Screenshot_2021-05-18-20-48-51-1](https://user-images.githubusercontent.com/84402549/118794513-f1baf280-b899-11eb-93af-edfb92b05260.png)
Good luck!

**Comment by Askevh** [comment]
Hi,
No need to make folders "emulated" and "0". Just the kivy folder should do the trick. See screenshot attached.
![118794513-f1baf280-b899-11eb-93af-edfb92b05260](https://user-images.githubusercontent.com/84402549/118795167-9e956f80-b89a-11eb-92a4-6f38c043cb38.png)

Good luck!

**Comment by Askevh** [comment]
Hi,
No need to make folders "emulated" and "0". Just the kivy folder should do the trick. See screenshot attached.
![Inked118794513-f1baf280-b899-11eb-93af-edfb92b05260_LI](https://user-images.githubusercontent.com/84402549/118795297-bc62d480-b89a-11eb-87ae-5cef673a1188.jpg)

Good luck!

**Comment by cbgd** [comment]
It works ! So easy finally !
thank you !!
